
sudo: false
language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
script:
  - "sbt clean coverage test"
  - 'sbt -Dlogger.resource=logback-test.xml test'
after_success: "sbt coveralls"
notifications:
  email:
    - leanne.northrop@gmail.com    
